[commands.list]
include = ["""has(labels.mind)"""]

[agent_types.worker]
parent_type = "claude"
trust_working_directory = true
# gross--have to move the generated settings into the right folder for us...
command = "mkdir -p $ROLE/.claude && cp .claude/settings.local.json $ROLE/.claude/settings.local.json && cd $ROLE && claude"
cli_args = """--dangerously-skip-permissions"""
model = "opus[1m]"
is_fast = true

[agent_types.verifier]
parent_type = "claude"
trust_working_directory = true
# gross--have to move the generated settings into the right folder for us...
command = "mkdir -p $ROLE/.claude && cp .claude/settings.local.json $ROLE/.claude/settings.local.json && cd $ROLE && claude"
cli_args = """--dangerously-skip-permissions"""
model = "opus[1m]"
is_fast = true

[commands.create]
connect = false
pass_env = ["MIND_NAME", "ANTHROPIC_API_KEY", "IS_SANDBOX", "IS_AUTONOMOUS"]
worktree_base_folder = "/worktree/"

[providers.modal]
is_enabled = false

[providers.docker]
is_enabled = false
