[commands.list]
include = ["""has(labels.mind)"""]

[agent_types.claude]
command = "mkdir -p $ROLE/.claude && cp .claude/settings.local.json $ROLE/.claude/settings.local.json && cd $ROLE && claude"
cli_args = """--dangerously-skip-permissions"""
auto_dismiss_dialogs = true

[agent_types.claude.settings_overrides]
model = "opus[1m]"
fastMode = true

[agent_types.worker]
parent_type = "claude"

[agent_types.verifier]
parent_type = "claude"

[commands.create]
connect = false
pass_env = ["MIND_NAME", "ANTHROPIC_API_KEY", "IS_SANDBOX", "IS_AUTONOMOUS"]

[create_templates.main]

[create_templates.dev]

[create_templates.docker]

[providers.modal]
is_enabled = false

[providers.docker]
is_enabled = false
