[commands.list]
include = ["""has(labels.mind)"""]

[agent_types.worker]
parent_type = "claude-mind"

[agent_types.verifier]
parent_type = "claude-mind"

[commands.create]
connect = false
pass_env = ["MIND_NAME", "ANTHROPIC_API_KEY", "IS_SANDBOX", "IS_AUTONOMOUS"]

[create_templates.main]
type = "claude-mind"
env = ["ROLE=thinking"]

[create_templates.dev]

[create_templates.docker]

[providers.modal]
is_enabled = false

[providers.docker]
is_enabled = false
