[pre_command_scripts]
create = ["""bash -c '[ -e ../.git ] || { echo "You must run create commands from your $ROLE folder." >&2; exit 2; }'"""]

[commands.list]
include = ["""--include 'has(labels.mind)'"""]

[commands.create]
type = "claude-mind"
source_path = "../"
pass-env = ["MIND_NAME"]
